# Generated by Django 2.2.1 on 2019-08-22 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='submisssion_date',
            new_name='submission_date',
        ),
    ]
